services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - my_shared_volume:/app/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: database/Dockerfile
    env_file:
      - .env
    command: gunicorn database.admin:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - bot
    volumes:
      - my_shared_volume:/app/uploads

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db_data:
  my_shared_volume: