"""update faq

Revision ID: 2348bf76b8cf
Revises: 6e64aae53e93
Create Date: 2025-04-23 14:23:11.243222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2348bf76b8cf'
down_revision: Union[str, None] = '6e64aae53e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('faq', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.drop_column('faq', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('faq', 'file_data')
    op.drop_column('faq', 'file_name')
    # ### end Alembic commands ###
