"""update faq

Revision ID: 87bfdfccc152
Revises: 2348bf76b8cf
Create Date: 2025-04-23 14:48:33.605347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87bfdfccc152'
down_revision: Union[str, None] = '2348bf76b8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.drop_column('faq', 'file_name')
    op.drop_column('faq', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('faq', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('faq', 'file_path')
    # ### end Alembic commands ###
