"""add faq_vtb

Revision ID: e4acb95c5c04
Revises: f2fa958a29f0
Create Date: 2025-07-03 14:32:39.789469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4acb95c5c04'
down_revision: Union[str, None] = 'f2fa958a29f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_vtb',
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_path_1', sa.String(length=255), nullable=True),
    sa.Column('file_path_2', sa.String(length=255), nullable=True),
    sa.Column('file_path_3', sa.String(length=255), nullable=True),
    sa.Column('file_path_4', sa.String(length=255), nullable=True),
    sa.Column('file_path_5', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_vtb')
    # ### end Alembic commands ###
